matrix:
  include:
    - language: java
      jdk: openjdk11
      dist: xenial
      before_install:
        - chmod +x gradlew
      script:
        - ./gradlew :mood-tracker-service:build
    - language: node_js
      node_js: 13.9.0
      dist: xenial
      services:
        - xvfb
      before_install:
        - cd mood-tracker-web
      install:
        - npm install
      script:
        - ng test

notifications:
  email: false
