version: '3.7'
services:
  web:
    build:
      context: ./../../
      dockerfile: Dockerfile
    image: mood-tracker-web:1.0.0
    container_name: mood-tracker-web
    ports:
      - 4200:4200
    networks:
      - uinet

networks:
  uinet:
